#Includes 28 properties

CODEMETA = {
    "name": None,
    "alternateName": None,
    "author": None,
    "version": None,
    "description": None,
    "citation": None,
    "codemeta:buildInstructions": None,
    "documentation": None,
    "softwareRequirements": None,
    "contributor": None,
    "license": None,
    "identifier": None,
    "dateCreated": None,
    "dateModified": None,
    "datePublished": None,
    "downloadUrl": None,
    "keywords": None,
    "codemeta:hasSourceCode": None,
    "releaseNotes": None,
    "codemeta:issueTracker": None,
    "programmingLanguage": None,
    "codemeta:developmentStatus": None,
    "codemeta:referencePublication": None,
    "codemeta:readme": None,
    "image": None,
    "logo": None,
    "applicationCategory": None,
    "discussionUrl": None
}

# Includes 39 properties
maSMP_SoftwareSourceCode = {
    "codeRepository": None,
    "programmingLanguage": None,
    "version": None,
    "description": None,
    "name": None,
    "url": None,
    "maSMP:versionControlSystem": None,
    "targetProduct": None,
    "archivedAt": None,
    "author": None,
    "citation": None,
    "identifier": None,
    "keywords": None,
    "license": None,
    "codemeta:readme": None,
    "maSMP:intendedUse": None,
    "codeSampleType": None,
    "runtimePlatform": None,
    "conditionsOfAccess": None,
    "contributor": None,
    "copyrightHolder": None,
    "dateModified": None,
    "datePublished": None,
    "discussionUrl": None,
    "maintainer": None,
    "codemeta:buildInstructions": None,
    "codemeta:issueTracker": None,
    "codemeta:referencePublication": None,
    "maSMP:developerDocumentation": None,
    "maSMP:learningResource": None,
    "maSMP:changelog": None,
    "maSMP:userDocumentation": None,
    "maSMP:deployInstructions": None,
    "maSMP:installInstructions": None,
    "maSMP:testInstructions": None
}

# Includes 42 properties
maSMP_SoftwareApplication = {
    "description": None,
    "name": None,
    "url": None, 
    "archivedAt": None,
    "author": None, 
    "citation": None,
    "codemeta:readme": None, 
    "maSMP:intendedUse": None,
    "releaseNotes": None, 
    "softwareVersion": None,
    "keywords": None,
    "license": None,
    "identifier": None, 
    "maSMP:developerDocumentation": None,
    "maSMP:userDocumentation": None,
    "maSMP:learningResource": None,
    "codemeta:referencePublication": None,
    "codemeta:buildInstructions": None,
    "codemeta:issueTracker": None, 
    "maSMP:changelog": None, 
    "maSMP:deployInstructions": None,
    "maSMP:installInstructions": None,
    "maSMP:testInstructions": None, 
    "memoryRequirements": None,
    "operatingSystem": None,
    "processorRequirements": None,
    "softwareRequirements": None,
    "storageRequirements": None,
    "conditionsOfAccess": None, 
    "contributor": None,
    "copyrightHolder": None,
    "dateModified": None, 
    "datePublished": None, 
    "discussionUrl": None,
    "maintainer": None
}

All_properties = {
  "name": None,
  "alternateName": None,
  "author": None,
  "version": None,
  "description": None,
  "citation": [],
  "codemeta:buildInstructions": None,
  "documentation": None,
  "softwareRequirements": None,
  "contributor": None,
  "license": None,
  "identifier": None,
  "dateCreated": None,
  "dateModified": None,
  "datePublished": None,
  "downloadUrl": None,
  "keywords": None,
  "codemeta:hasSourceCode": None,
  "releaseNotes": None,
  "issueTracker": None,
  "programmingLanguage": None,
  "codemeta:developmentStatus": None,
  "codemeta:referencePublication": None,
  "codemeta:readme": None,
  "image": None,
  "logo": None,
  "applicationCategory": None,
  "discussionUrl": None,
  "codeRepository": None,
  "url": None,
  "maSMP:versionControlSystem": None,
  "targetProduct": None,
  "archivedAt": None,
  "maSMP:intendedUse": None,
  "codeSampleType": None,
  "runtimePlatform": None,
  "conditionsOfAccess": None,
  "copyrightHolder": None,
  "maintainer": None,
  "maSMP:developerDocumentation": None,
  "maSMP:learningResource": None,
  "maSMP:changelog": None,
  "maSMP:userDocumentation": None,
  "maSMP:deployInstructions": None,
  "maSMP:installInstructions": None,
  "maSMP:testInstructions": None,
  "softwareVersion": None,
  "memoryRequirements": None,
  "operatingSystem": None,
  "processorRequirements": None,
  "storageRequirements": None,
}

to_be_removed = {
    "isAccessibleForFree": None,
    "maSMP:input": None,
    "maSMP:output": None,
    "maSMP:testedWith": None,
    "sameAs": None, 
    "installUrl": None,
    "softwareHelp": None,
}

# HF_API_KEY = "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"

# Llama 2
HF_API_KEY = "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"